# numpy >> numerical python

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
lis = [1, 2, 3, 4, "pwskills"]
type(lis)

list

# numpy stores the data in an array
# An array is a container used to store the data of same datatype

# Why_numpy
# Computation is fast >> due to array >> continuous memory allocation
# mathematical computation

In [5]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [6]:
l = [1, 2, 3, 4, 5.1]
arr = np.array(l)
arr

array([1. , 2. , 3. , 4. , 5.1])

In [7]:
l = [1, 2 , 3, 4.1, "ayush"]
arr = np.array(l)
arr

array(['1', '2', '3', '4.1', 'ayush'], dtype='<U32')

# arr stores homogeneous data

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim # dimension

1

In [10]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr1.ndim

2

In [17]:
mat = np.matrix([1, 2, 3, 4])
type(mat)

numpy.matrix

In [18]:
mat1 = np.matrix([[1, 2], [3, 4]])
mat1

matrix([[1, 2],
        [3, 4]])

# Matrix is a specialized array, 2 dimensional

# more way to convert array

In [14]:
l = [1, 2, 3, 4]
np.asarray(l)

array([1, 2, 3, 4])

In [15]:
mat

matrix([[1, 2, 3, 4]])

In [16]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [20]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [22]:
np.asanyarray(mat) # convert the input to an ndarray, but pass ndarray subclass through.

matrix([[1, 2, 3, 4]])

In [23]:
t = ([1, 2, 3], [4, 5, 6]) # tuple into array
type(t)

tuple

In [24]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [27]:
arr[0]

1

In [28]:
arr[0] = 500
arr

array([500,   2,   3,   4,   5])

In [29]:
a = arr

In [30]:
a

array([500,   2,   3,   4,   5])

In [31]:
arr[0] = 1000

In [32]:
a # change in array also lead to change in a >> shallow copy

array([1000,    2,    3,    4,    5])

In [33]:
a = arr.copy()
a

array([1000,    2,    3,    4,    5])

In [34]:
arr

array([1000,    2,    3,    4,    5])

In [35]:
arr[0] = 2

In [36]:
arr

array([2, 2, 3, 4, 5])

In [37]:
a

array([1000,    2,    3,    4,    5])

# To create an array >> np.array, np.anarray, np.asanyarray, deep copy and shallow copy

# multiple ways to generate an array

In [41]:
arr1 = np.fromfunction(lambda i, j : i == j, (3, 3)) # construct an array by executing a function over each coordinate

In [42]:
arr1.ndim

2

In [43]:
arr1.shape # shape of array

(3, 3)

In [44]:
arr1.size # no of elements in an array

9

In [45]:
arr2 = np.fromfunction(lambda i, j : i * j, (3, 3))
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [46]:
for i in range(5):
    print(i)

0
1
2
3
4


In [47]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [48]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [49]:
(i for i in range(5))

<generator object <genexpr> at 0x71f4661f4580>

In [51]:
iterable = (i for i in range(5))
np.fromiter(iterable, int) # create a new 1-dimensional array from an iterable object

array([0, 1, 2, 3, 4])

In [55]:
np.fromstring('22 23 24 25', sep=" ") #values should be numerical

array([22., 23., 24., 25.])

In [56]:
np.fromstring('Ajay Bijay Sanjay', sep=" ")

/tmp/ipykernel_13153/3088906135.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Ajay Bijay Sanjay', sep=" ")


array([], dtype=float64)

In [57]:
# for string character you have to use split
string = 'Ajay,Bijay,Sanjay'
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [58]:
np.fromstring('22,23,24', sep=",")

array([22., 23., 24.])

In [59]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
range(10)

range(0, 10)

In [61]:
#other method of numpy >> to generate a sequence of number
np.arange(1, 10, 0.1) # return evenly spaced values within a given interval

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [62]:
np.linspace(1, 5, 10) # return evenly spaced numbers over a specified interval

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [63]:
np.logspace(1, 5, 10) # Return numbers spaced evenly on a log scale.

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [64]:
np.logspace(1, 5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])