In [9]:
import numpy as np

In [10]:
a = np.zeros(5) # Return a new array of given shape and type, filled with zeros
a

array([0., 0., 0., 0., 0.])

In [11]:
a.ndim  # dimension of array

1

In [12]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
b.ndim

2

In [14]:
c = np.ones((3, 4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.array([[2, 3, 4], [2, 3, 4]])

array([[2, 3, 4],
       [2, 3, 4]])

In [16]:
np.twos(3) # does not exists

AttributeError: module 'numpy' has no attribute 'twos'

# 3 dimension array

In [17]:
arr = np.zeros((1, 2, 3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
arr.ndim # 3 dimension

3

In [19]:
np.zeros((1, 2, 3, 4)) # 4 dimension array and it goes on

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [20]:
arr = np.ones((3, 4))

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr + 5 # add 5 to every element of the array

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
arr - 1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.eye(3) # Return a 2-D array with ones on the diagonals and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3, dtype=int)  # change the type of element from float to integer

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
np.empty((3, 4))  # Return a new array of given shape and type, without initializing entries.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# random module

In [28]:
import random
random.choice((1, 2, 3, 4, 5, 6)) # display random number from the given number

1

In [29]:
random.choice("Ayush")

'A'

In [30]:
random.randrange(1, 20)

1

In [31]:
random.random() # a random number is generated between 0 (included) and 1 (excluded)

0.39692469804467745

In [32]:
lis = [1, 2, 3, 4, 5]

In [33]:
lis

[1, 2, 3, 4, 5]

In [34]:
random.shuffle(lis)
lis

[5, 4, 2, 1, 3]

In [35]:
random.uniform(7, 15) # Get a random number in the range [a, b) or [a, b] depending on rounding.

13.423314216392999

# random number related concepts in array

In [36]:
np.array([])

array([], dtype=float64)

In [37]:
np.random.random_sample() # Return random floats in the half-open interval [0.0, 1.0).

0.6668570863419303

In [38]:
np.random.random_sample((5, ))

array([0.68738506, 0.29193066, 0.41116916, 0.00636581, 0.69750352])

In [39]:
np.random.rand(1)

array([0.8049015])

In [40]:
np.random.rand(2, 3)

array([[0.14376647, 0.19319779, 0.37596972],
       [0.2014936 , 0.29914795, 0.33224283]])

In [41]:
np.random.randn(2, 3)

array([[-2.26523485, -2.41557751,  0.05999493],
       [-0.89138354,  1.60323555, -0.23626798]])

In [42]:
arr = np.random.randint(1, 5, size=(3, 4))

In [44]:
arr.shape

(3, 4)

In [45]:
arr.size

12

# reshaping the array

In [ ]:
# array size will not change, always reshape parameter should be multiplication of original array size
arr.reshape(2, 6) # size will be same

array([[1, 4, 4, 1, 4, 4],
       [3, 4, 2, 3, 2, 3]])

In [49]:
arr.reshape(2, 3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [ ]:
# case when you don't know in reshape what should be the column count, just put (-integer)

arr.reshape(3, -1)

array([[1, 4, 4, 1],
       [4, 4, 3, 4],
       [2, 3, 2, 3]])

In [51]:
arr.reshape(-1, 3)

array([[1, 4, 4],
       [1, 4, 4],
       [3, 4, 2],
       [3, 2, 3]])

In [52]:
arr.reshape(12, 1).base # to see the original array

array([[1, 4, 4, 1],
       [4, 4, 3, 4],
       [2, 3, 2, 3]])

In [53]:
arr.reshape(2, 2, 3)

array([[[1, 4, 4],
        [1, 4, 4]],

       [[3, 4, 2],
        [3, 2, 3]]])

In [55]:
arr.reshape(4, 3, 1) # 3 columns and 1 row repeated 4 times in the third dimension

array([[[1],
        [4],
        [4]],

       [[1],
        [4],
        [4]],

       [[3],
        [4],
        [2]],

       [[3],
        [2],
        [3]]])

# conditions with array

In [56]:
arr1 = np.random.randint(1, 10, (5, 6))
arr1

array([[9, 3, 2, 6, 5, 3],
       [1, 7, 4, 8, 3, 5],
       [6, 9, 6, 6, 8, 7],
       [9, 8, 6, 3, 3, 1],
       [6, 7, 8, 2, 6, 3]])

In [57]:
arr1.ndim

2

In [58]:
arr1.size

30

In [59]:
arr1 > 5

array([[ True, False, False,  True, False, False],
       [False,  True, False,  True, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False,  True, False]])

In [60]:
arr1[arr1 > 5]

array([9, 6, 7, 8, 6, 9, 6, 6, 8, 7, 9, 8, 6, 6, 7, 8, 6])

In [61]:
arr1[arr1 < 5]

array([3, 2, 3, 1, 4, 3, 3, 3, 1, 2, 3])

In [62]:
arr1[0]

array([9, 3, 2, 6, 5, 3])

In [63]:
arr1[1][2]

4

In [ ]:
arr1[0:2] # print row from 0 to 2 - 1

array([[9, 3, 2, 6, 5, 3],
       [1, 7, 4, 8, 3, 5]])

In [ ]:
arr1[0:3, [0, 2]] # give 0 to 2 rows and 0th and 2nd column

array([[9, 2],
       [1, 4],
       [6, 6]])

In [ ]:
# slicing both rows and columns
arr1[0:3, 1:2]

array([[3],
       [7],
       [9]])

In [67]:
# mathematical operations on two arrays

In [70]:
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))

In [72]:
arr1

array([[7, 8, 5],
       [5, 6, 5],
       [7, 9, 5]])

In [73]:
arr2

array([[5, 4, 5],
       [1, 6, 1],
       [5, 5, 6]])

In [ ]:
arr1 + arr2 # indexwise element addition

array([[12, 12, 10],
       [ 6, 12,  6],
       [12, 14, 11]])

In [ ]:
arr1 - arr2 # indexwise element substraction

array([[ 2,  4,  0],
       [ 4,  0,  4],
       [ 2,  4, -1]])

In [ ]:
arr1 * arr2  # indexwise element multiplication

array([[35, 32, 25],
       [ 5, 36,  5],
       [35, 45, 30]])

In [77]:
arr1 / arr2 # indexwise element division

array([[1.4       , 2.        , 1.        ],
       [5.        , 1.        , 5.        ],
       [1.4       , 1.8       , 0.83333333]])

In [78]:
arr1, arr2

(array([[7, 8, 5],
        [5, 6, 5],
        [7, 9, 5]]),
 array([[5, 4, 5],
        [1, 6, 1],
        [5, 5, 6]]))

In [79]:
# matrix multiplication >> different from index multiplication

In [80]:
arr1 @ arr2

array([[ 68, 101,  73],
       [ 56,  81,  61],
       [ 69, 107,  74]])

In [ ]:
np.dot(arr1, arr2) # another way of multiplication

array([[ 68, 101,  73],
       [ 56,  81,  61],
       [ 69, 107,  74]])

In [82]:
arr1 / 0

/tmp/ipykernel_296215/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [83]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
a = np.array([1, 2, 3, 4])


In [85]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [87]:
a = np.array([[1, 2, 3, 4, 5]])
a.T # transpose

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [88]:
np.sqrt(arr1)

array([[2.64575131, 2.82842712, 2.23606798],
       [2.23606798, 2.44948974, 2.23606798],
       [2.64575131, 3.        , 2.23606798]])

In [89]:
np.log10(arr1)

array([[0.84509804, 0.90308999, 0.69897   ],
       [0.69897   , 0.77815125, 0.69897   ],
       [0.84509804, 0.95424251, 0.69897   ]])

In [90]:
np.exp(arr1)

array([[1096.63315843, 2980.95798704,  148.4131591 ],
       [ 148.4131591 ,  403.42879349,  148.4131591 ],
       [1096.63315843, 8103.08392758,  148.4131591 ]])

In [91]:
np.min(arr1)

5

In [92]:
np.max(arr1)

9